### ISSUE TITLE
Not working go back button in Svelte Admin page

### ISSUE THREAD

**Issue by lkim227** [SveltyCMS/SveltyCMS#161]
### Describe the problem

There is no any animation. And if click the go back button in browser, then this Svelte projects navigate to the non URL status. In other words, it is because of that not used node module so that this Svelte SPA application can work as a SSR application.  

### Describe the proposed solution

This is because of whole resource was rendered on one browser as a SPA. So browswer must save whole urls according to pages and the page content must be changed by the browswer url, not only by Svelte framework routers.

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rar9** [comment]
Thanks. All back buttons are going to be fixed in next commit.

Main branch will be killed today, to be replaced by router branch.

Delete database and  run cli installer as config as there is no migration.
